import Navigation from '@/components/ui/navigation';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { FileText, Building, Globe, DollarSign, AlertTriangle, Briefcase, Shield, Award } from 'lucide-react';

export default function Disclosures() {
  const sections = [
    {
      icon: Building,
      title: 'Business Information',
      content: `Codexel.ai is operated by:
      
Company Name: Codexel Technologies Inc.
Type: Delaware C-Corporation
Founded: 2024
Headquarters: San Francisco, California, USA
Business Registration: #87654321

Our platform serves developers, entrepreneurs, and businesses worldwide with AI-powered development tools.`
    },
    {
      icon: Briefcase,
      title: 'Service Disclaimers',
      content: `AI-Generated Code:
• All code generated by our AI models should be reviewed before production use
• We do not guarantee the accuracy, completeness, or security of generated code
• Users are responsible for testing and validating all outputs
• AI responses may occasionally produce incorrect or biased information

Service Availability:
• We strive for 99.9% uptime but do not guarantee uninterrupted service
• Scheduled maintenance occurs during off-peak hours
• Emergency maintenance may occur without notice`
    },
    {
      icon: DollarSign,
      title: 'Financial Disclosures',
      content: `Pricing Transparency:
• All prices are listed in USD unless otherwise specified
• Taxes may apply based on your location
• Exchange rate fluctuations may affect international payments

Refund Policy:
• Monthly subscriptions: No refunds for partial months
• Annual subscriptions: Pro-rated refunds available within 30 days
• Enterprise contracts: Subject to individual agreements

Affiliate Relationships:
• We may earn commissions from third-party services we recommend
• Affiliate relationships do not affect our pricing or recommendations`
    },
    {
      icon: Globe,
      title: 'Data Processing',
      content: `Data Centers:
• Primary: United States (Virginia, Oregon)
• Secondary: European Union (Ireland, Germany)
• Asia-Pacific: Singapore, Japan

Third-Party Services:
• OpenAI - AI model provider
• Anthropic - AI model provider
• Google Cloud - Infrastructure and AI services
• Stripe - Payment processing
• Cloudflare - Security and CDN

All third-party services are vetted for security and compliance.`
    },
    {
      icon: Shield,
      title: 'Security Certifications',
      content: `Compliance:
• GDPR Compliant (European users)
• CCPA Compliant (California users)
• SOC 2 Type II (in progress)
• ISO 27001 (planned 2025)

Security Measures:
• 256-bit SSL encryption
• Regular penetration testing
• Bug bounty program
• 24/7 security monitoring
• Multi-factor authentication available`
    },
    {
      icon: AlertTriangle,
      title: 'Risk Disclosures',
      content: `Investment Risks:
• Building applications requires time and effort
• Market success is not guaranteed
• Technology landscape changes rapidly

Platform Risks:
• AI models may be updated or deprecated
• Features may change based on user feedback
• Pricing may be adjusted with notice

User Responsibilities:
• Backup your code regularly
• Maintain secure passwords
• Monitor your usage and billing
• Comply with all applicable laws`
    },
    {
      icon: Award,
      title: 'Testimonials Disclaimer',
      content: `Customer Success Stories:
• Results shown are not typical
• Individual results may vary significantly
• Testimonials represent individual experiences
• Past performance does not guarantee future results

Marketing Claims:
• "10x faster" based on internal testing
• ROI calculations are estimates only
• Productivity gains depend on user expertise
• Success requires active platform usage`
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-950 via-purple-950/20 to-gray-950">
      <Navigation />
      
      <div className="container mx-auto px-4 py-16">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <h1 className="text-4xl font-bold mb-4 bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent">
              Business Disclosures
            </h1>
            <p className="text-gray-400">
              Transparency and Trust in AI Development
            </p>
          </div>

          <Card className="backdrop-blur-xl bg-white/5 border-white/10 mb-8">
            <CardContent className="p-6">
              <p className="text-gray-300 leading-relaxed">
                At Codexel.ai, we believe in complete transparency with our users. This page contains important disclosures about our business operations, partnerships, and service limitations. We encourage you to review this information to make informed decisions about using our platform.
              </p>
            </CardContent>
          </Card>

          <div className="space-y-6">
            {sections.map((section, index) => (
              <Card key={index} className="backdrop-blur-xl bg-white/5 border-white/10 hover:bg-white/10 transition-colors">
                <CardHeader>
                  <CardTitle className="flex items-center gap-3 text-white">
                    <section.icon className="w-5 h-5 text-purple-400" />
                    {section.title}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-300 whitespace-pre-line">
                    {section.content}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>

          <Card className="backdrop-blur-xl bg-purple-900/20 border-purple-500/20 mt-8">
            <CardContent className="p-6">
              <h3 className="text-lg font-semibold text-white mb-2">
                Questions or Concerns?
              </h3>
              <p className="text-gray-300 mb-4">
                We're committed to transparency and are happy to answer any questions about our business practices.
              </p>
              <div className="space-y-2 text-gray-400">
                <p>General Inquiries: info@codexel.ai</p>
                <p>Legal Questions: legal@codexel.ai</p>
                <p>Security Concerns: security@codexel.ai</p>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}